name: Flask Docker CI

on:
    push:
        branches:
            - main


env:
    IMAGE_NAME: flask-demo

jobs:

    build-test-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Build Docker Image 
              run: | 
                docker build \ 
                -t nikhilj1402/flask-demo:${{ github.sha }} \
                ./flaskapp

        



